version: "3.3"

services:
  blog_backend:
    image: liuzhenghuan/enlighten_backend:dev_20210805
    volumes:
      - ./blog_backend/logs:/code/logs
    ports:
      - "8000:8000"
    command:  gunicorn boluomi.wsgi:application --bind 0.0.0.0:8000 --workers 2

  blog_nginx:
    image: nginx
    depends_on:
      - blog_backend
    volumes:
      - ./data/blog_nginx/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./data/blog_nginx/dist/:/web/dist/
    ports:
      - "80:80"

#  postgresql:
#    image: postgresql
#    volumes:
#      - ./data/mysql:/var/lib/mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: mysql
#      MYSQL_USER: root
#      MYSQL_PASSWORD: mysql
#      TZ: Asia/Shanghai

  redis:
    image: redis
    volumes:
      - ./data/redis/config/redis_master.conf:/usr/local/etc/redis/redis.conf
      - ./data/zhiyuan_extract_redis/data:/data
    command: redis-server /usr/local/etc/redis/redis.conf