version: "3.3"

services:
  blog_backend:
    image:
    volumes:
      - ./blog_backend/logs:/code/logs
    ports:
      - "8000:8000"

  blog_nginx:
    images:
    depends_on:
      - blog_backend
    volumes:
      ./data/blog_nginx/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

  mysql:
    image: mysql:8.0.21
    volumes:
      - ./data/mysql:/var/lib/mysql

  redis:
    image: redis

volumes:
  db-data:
